settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: app
  path: .
  commands:
    test:
      status: true
      method: go test -v
    build:
      status: true
      method: go build -o webapp
    run:
      status: true
      method: ./webapp
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    scripts:
    - type: after
      global: true
      command: rm webapp
