FROM golang:1.13.12 as builder

WORKDIR /go/src/app

RUN groupadd -g 10001 app \
      && useradd -u 10001 -g app app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/app

FROM scratch

COPY --from=builder /go/bin/app /go/bin/app
COPY --from=builder /etc/group /etc/group
COPY --from=builder /etc/passwd /etc/passwd

EXPOSE 3030

USER app

ENTRYPOINT ["/go/bin/app"]
